// <auto-generated />
using System.CodeDom.Compiler;
using System.Data.Entity.Migrations;
using System.Data.Entity.Migrations.Infrastructure;
using System.Resources;

[GeneratedCode("EntityFramework.Migrations", "6.0.2-21211")]
public sealed partial class RemoveColumnUrlFriendlyName : IMigrationMetadata
{
    private readonly ResourceManager Resources = new ResourceManager(typeof(RemoveColumnUrlFriendlyName));
    
    string IMigrationMetadata.Id
    {
        get { return "201404021339072_RemoveColumnUrlFriendlyName"; }
    }
    
    string IMigrationMetadata.Source
    {
        get { return null; }
    }
    
    string IMigrationMetadata.Target
    {
        get { return Resources.GetString("Target"); }
    }
}
